--- #YAML:1.0
name:                FindBin-libs
version:             1.36
abstract:            Locate and 'use lib' directories along
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Cwd:                           0
    File::Spec:                    0
    FindBin:                       0
    strict:                        0
    Symbol:                        0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
