---
abstract: "FindBin::libs - locate and a 'use lib' or export \ndirectories based on .\n"
author:
  - 'Steven Lembark <lembark@wrkhors.com'
build_requires: {}
configure_requires:
  Module::Build: '0.4005'
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FindBin-libs
provides:
  FindBin::libs:
    file: lib/FindBin/libs_curr.pm
    version: v1.64.1
requires:
  Carp: '0'
  Cwd: '0'
  File::Spec: '0'
  File::Temp: '0'
  FindBin: '0'
  List::Util: '0'
  Symbol: '0'
  Test::More: '0'
  strict: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '1.9'
