# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FindBin-libs
version:      0.12
version_from: lib/FindBin/libs.pm
installdirs:  site
requires:
    Carp:                          0
    Cwd:                           0
    FindBin:                       0
    strict:                        0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
