# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         FindBin-libs
version:      1.34
version_from: 
installdirs:  site
requires:
    Carp:                          0
    Cwd:                           0
    File::Spec:                    0
    FindBin:                       0
    strict:                        0
    Symbol:                        0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
