---
abstract: "locate and a 'use lib' or export  directories based on $FindBin::Bin."
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: FindBin-libs
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Cwd: '0'
  File::Spec: '0'
  File::Temp: '0'
  FindBin: '0'
  List::Util: '0'
  Symbol: '0'
  Test::More: '0'
  strict: '0'
version: '2.00'
